import type { Metadata } from "next";
import { Noto_Sans, Geist_Mono, Instrument_Sans } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import localFont from "next/font/local";

const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});
const instrumentSans = Instrument_Sans({
  variable: "--font-instrument-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

const outdoorInks = localFont({
  src: "./fonts/OutdoorsInks_Regular.otf",
  variable: "--font-outdoor-inks",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${notoSans.variable} ${geistMono.variable} ${instrumentSans.variable} ${outdoorInks.variable} antialiased`}
      >
        <main className="max-w-6xl px-4 py-10 mx-auto">
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  );
}
